### ISSUE TITLE
Remove error count, warning count when `0`

### ISSUE THREAD

**Issue by wooorm** [vfile/vfile-reporter#1]
`✖ 1 message (0 errors, 1 warning)` > `✖ 1 message (1 warning)`.

**Comment by sindresorhus** [comment]
Since there's only one type now, having `message` feels a bit verbose. I would rather go with:

```
⚠ 1 warning
```

See: https://github.com/sindresorhus/log-symbols

**Comment by wooorm** [comment]
![screen shot 2015-08-20 at 9 21 00 p m](https://cloud.githubusercontent.com/assets/944406/9393272/6342758a-4781-11e5-93be-427ffc56d6d9.png)

How about these? Just `1 warning` or `1 error` in the case of one type, otherwise a total and separate counts?

This would result in a prettier report for programs with only one type of message, but an “extensive” summary for programs which have more types (e.g., mdast, retext).

**Comment by sindresorhus** [comment]
Oh, didn't realize this is used for other things too. I meant it mostly as a UI tweak for Al*\* linter, since we only use warnings there.

**Comment by wooorm** [comment]
😉 Alright I’ll push this, thanks for the suggestion, it’s actually better this way!
