### ISSUE TITLE
Warning doesn't include message

### ISSUE THREAD

**Issue by tmcw** [vfile/vfile-reporter#2]
``` js
var VFile = require('vfile'),
  reporter = require('vfile-reporter');

var f = new VFile();
f.warn('hi');
console.log(reporter(f));
```

This gives the output

``` js
<stdin>
        1:1  warning
```

The warning message is discarded when it is [assigned to the stack](https://github.com/wooorm/vfile-reporter/blob/master/index.js#L218). I'm not quite sure how this is working in tests, will dig a bit more

**Comment by wooorm** [comment]
Ah darn, probably has to do with 1.1.1 and 1.1.2 of vfile (https://github.com/wooorm/vfile/commits/master) hope to come up with a fix soon.

**Comment by wooorm** [comment]
This is fixed, thanks for reporting, let me know how documentationjs/documentation#198 goes!
