### ISSUE TITLE
Unnecessary whitespace printed when `quiet`

### ISSUE THREAD

**Issue by DaelDe** [vfile/vfile-reporter#20]
### Subject of the issue
When running the reporter with `console.error(reporter(files, {quiet: true}))` it prints an empty line on stderr. I would expect that nothing is printed when there are no messages (all files are clean).

### Your environment

*   **OS**: Win10
*   **Packages**: 
*   **Env**: node v11.10.0

### Steps to reproduce
```
var vfile = require('vfile')
var reporter = require('vfile-reporter')

var one = vfile({path: 'test/fixture/1.js'})
var two = vfile({path: 'test/fixture/2.js'})

console.error(reporter([one, two], {quiet: true}))
```
Just comment the last line and the difference in the output is clear.

### Expected behaviour
No empty line shout be printed.

### Actual behaviour
An empty line is printed.

**Comment by wooorm** [comment]
The output of the `reporter(...)` call in this case is an empty string, but `console.error` (and `console.log`) always print a line feed at the end: this is a “feature” of that function, not something we can change here.

**Comment by DaelDe** [comment]
@wooorm well, I would expect that there is no call to console.log when nothing is to be printed out.
