### ISSUE TITLE
The module only supports ESM but example is in commonjs

### ISSUE THREAD

**Issue by malcolm-kee** [vfile/vfile-reporter#22]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: TODO

### Steps to reproduce

1.  TODO
2.  TODO

Link to code example: TODO

### Expected behavior

TODO

### Actual behavior

TODO

**Comment by wooorm** [comment]
@malcolm-kee Please adhere to the template.
