### ISSUE TITLE
Update NPM readme to have ESM example

### ISSUE THREAD

**Issue by teinett** [vfile/vfile-reporter#23]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vfile-reporter

### Steps to reproduce

Go to NPM: https://www.npmjs.com/package/vfile-reporter

Read the readme text. 

### Expected behavior

Example in NPM is updated with the code from https://github.com/vfile/vfile-reporter#readme:

```
import {VFile} from 'vfile'
import {reporter} from 'vfile-reporter'

var one = new VFile({path: 'test/fixture/1.js'})
var two = new VFile({path: 'test/fixture/2.js'})

one.message('Warning!', {line: 2, column: 4})

console.error(reporter([one, two]))
```

### Actual behavior

The readme of NPM package has example of not-ESM version.

```
var vfile = require('vfile')
var reporter = require('vfile-reporter')

var one = vfile({path: 'test/fixture/1.js'})
var two = vfile({path: 'test/fixture/2.js'})

one.message('Warning!', {line: 2, column: 4})

console.error(reporter([one, two]))
```
<img width="789" alt="NPM" src="https://user-images.githubusercontent.com/1038168/124300024-c3058c80-db66-11eb-8a00-94c273641bcb.png">

**Comment by wooorm** [comment]
Thanks, fixed in https://github.com/vfile/vfile-reporter/releases/tag/7.0.1
