### ISSUE TITLE
One of dep requires node API, that breaks the browser build

### ISSUE THREAD

**Issue by linonetwo** [vfile/vfile-reporter#24]
### Initial checklist

- [X] I read the [support docs](https://github.com/vfile/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/vfile/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/vfile/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Avfile&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"vfile-reporter": "^7.0.2"

### Link to runnable example

https://github.com/linonetwo/template-based-generator-template/tree/84fa27aa65db3fd10af140aa5cc7a9a815a0f326

### Steps to reproduce

visit demo/useTemplateGeneration.ts , uncomment vfile-reporter, and run` npm run dev:demo`

You can see error caused by node API in the browser.

### Expected behavior

No node api when using in the browser.

### Actual behavior

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
process (imported by node_modules/vfile-reporter/node_modules/supports-color/index.js, node_modules/vfile-reporter/node_modules/has-flag/index.js)
tty (imported by node_modules/vfile-reporter/node_modules/supports-color/index.js)
os (imported by node_modules/vfile-reporter/node_modules/supports-color/index.js)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
process (guessing 'process$2')
os (guessing 'os')
tty (guessing 'tty')
```

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
I’m open to accepting a PR that uses a `browser` field similar to how `unist-util-inspect` does some of this: https://github.com/syntax-tree/unist-util-inspect/blob/d56810089d0ae71b65917256002e6094e9dd6eaa/package.json#L29-L34.
But then using `supports-color` in the normal/Node.js version.

Can you work on that?

**Comment by linonetwo** [comment]
Ok, I can try this, just after I finish my hackathon project!

Looks like a simple first issue.

**Comment by ChristianMurphy** [comment]
@linonetwo friendly ping, is this still something you're interested in?

**Comment by linonetwo** [comment]
Wow, barely forget, will try this today.
