### ISSUE TITLE
Reports containing errors should make it exit with code 1

### ISSUE THREAD

**Issue by sindresorhus** [vfile/vfile-reporter#3]
This is what ESLint does.

Example:

``` js
const VFile = require('vfile');
const reporter = require('vfile-reporter');

const f = new VFile();
f.quiet = true;
f.fail('hi');
console.log(reporter(f));
```

**Comment by wooorm** [comment]
Interesting! How are you using `vfile-reporter`?

My initial feels are that it’s out of scope, as I intend the project to be more like just an output generator, and not always as the final thing.

P.S. There’s also `vfile#hasFailed()`, which could be used below your example code like so:

``` js
// ...
process.exit(f.hasFailed() ? 1 :0);
```

**Comment by wooorm** [comment]
Closing as I don’t think this should be done by a reporter! I’ve opened a new issue for a feature which might make `hasFailed` useful for warnings as well: https://github.com/wooorm/vfile/issues/7.

**Comment by sindresorhus** [comment]
Agreed, but you should add that to the docs. It's easy to assume it works like that when you have the sentence:

> Originally forked from ESLint’s stylish reporter, but with some coolness added.

**Comment by wooorm** [comment]
I can’t grasp that, I mean, no ESLint formatter handles exit-codes. And I don’t think they should. No non-CLI should deal with exit codes.

This also sounds sort-of double: the whole reason of `fail` is to throw fatal errors to stop node (with non-zero), if you’re explicitly preventing that from happening by settings `quiet: true`, surely you must handle the exit code too?

**Comment by sindresorhus** [comment]
You're right. No sure what I was thinking...

Unrelated to this issue, but if VFile exposed an `errorCount` I could do this: https://github.com/sindresorhus/xo/blob/bb76a2d28817a176056c2da37f09112810643b4a/cli.js#L87

**Comment by wooorm** [comment]
👍

> Unrelated to this issue, but if VFile exposed an errorCount I could do this: https://github.com/sindresorhus/xo/blob/bb76a2d28817a176056c2da37f09112810643b4a/cli.js#L87

Yeah, that’d be very useful indeed!

TBH, I’m thinking of moving VFile to more of just a plain object, or at least removing lots of methods, that way an external module could do exactly the thing you want, like calculating an exit-code from a file, much better!

**Comment by sindresorhus** [comment]
I don't think it should be a plain object. There's benefit in being able to detect that it's a VFile.

Let's continue this in a new issue → https://github.com/wooorm/vfile/issues/8
